小修改，封装响应
leeeduke/revTongYi pull request #9
Opened 2024-03-17 04:32 UTC by old-dream321

### 1.在ask中加入sessionId参数，便于更好的连续对话
（主要是我一直是这么用的）
```python
chatbot = qianwen.Chatbot(
    cookies_str=""
)
chatbot.sessionId = "<sessionId>"
```
如果不传入，则会使用对象中的sessionId

### 2.封装响应（这样以后再怎么改都不用重新适配了）
```json
{
    "contentType": "text",
    "contents": ["你好"], 
    "msgStatus": "finished", 
    "msgId": "<msgId>", 
    "parentMsgId": "<parentMsgId>", 
    "sessionId": "<sessionId>"
}

```
本人高中生，一周也只有一天假期，确实有些地方没有考虑周全，望谅解（）

2024-03-17 08:28 UTC, leeeduke commented
感谢贡献，提醒一下，你机器上的 git 配置中的 user.email 可能和你 github 账户的 email 不同，导致仓库没法认定你为 contributor，建议你检查一下。

2024-03-17 08:41 UTC, leeeduke commented
基本没问题，但我更倾向把响应包装在一个类里面，一步到位。

定义一个 `Response` 类，里面包装了 `sessionId` `messageId` `content` 等信息供使用者获取，也更加清晰。

2024-03-17 08:43 UTC, leeeduke requested changes

2024-03-17 08:43 UTC, leeeduke commented on README.md
> +```
改为使用对象返回响应信息

2024-03-17 08:43 UTC, leeeduke commented on revTongYi/qianwen.py
> +
辛苦稍微设计一下响应类和包装形式

2024-03-17 08:53 UTC, old-dream321 commented
> 基本没问题，但我更倾向把响应包装在一个类里面，一步到位。
> 
> 定义一个 `Response` 类，里面包装了 `sessionId` `messageId` `content` 等信息供使用者获取，也更加清晰。

只有消息的响应做还是所有的，只有消息的响应做的话不够统一，所有都做感觉没必要

2024-03-17 08:56 UTC, leeeduke commented
只做ask的响应吧，其他的接口一般没改动。wanxiang 的也不用管先。

2024-03-17 13:49 UTC, old-dream321 commented
做好了，现在用了一个基于dict类的子类来实现，所有的"resp.key"都等同于"resp[key]"，所以现在有两种获取值的方式，对于所有响应都适用

2024-03-17 14:24 UTC, old-dream321 commented
> 做好了，现在用了一个基于dict类的子类来实现，所有的"resp.key"都等同于"resp[key]"，所以现在有两种获取值的方式，对于所有响应都适用

感觉你的意思应该是输入"."之后会有提示吧，好像不太一样，只能新开一个文件专门写响应模板了

2024-03-19 06:21 UTC, leeeduke requested changes
主要的更改为对象返回的思路没有问题，但设计上似乎没有达到我们的目标。

这个`以类的形式包装返回数据`并不仅仅是包装，而是要我们确定一个类的格式，作为中间态 连接接口和调用方。

目前使用 QianWenResponse 类包装数据，相比起之前的纯dict返回是有进步的。但我们需要明确我们的需求：我们定义一个类，这个类的结构相较于接口返回的数据格式来说是相对稳定的，用户只需要知道类中的成员即可使用。

## 总结如下：

- 一个类中包装`返回内容列表`、`消息ID`、`SessionId` 等信息
- 确定的类结构，仅在类结构无法满足新接口时修改
  
    ```markdown
    这种情况下什么时候需要修改类结构？

    例如我们类中保存一个 content: str
    
    class ExampleResponse:
        content: str

    但最新接口中支持返回多条响应了，我们就需要修改为

    class ExampleResponse
        content: list[str]

    遵循这样的原则：我们一般不改动这个类的结构（否则用户会对我们怨声载道），改动最小化，仅必须改动时改动，尽量只加不删改。所以目前需要设计一种`为未来考虑的格式`
    ```
- 分离`接口返回数据`到`类的对象`的转换过程，建议写到类的构造器中：传入接口返回的数据dict，类中转换为自身对象。这样做到了 请求过程 和 数据封装过程 的解藕

## 参考结构

```python

class QianWenContent:
    
    content: str

    contentType: str
  
    id: str

    role: str

    status: str

class QianWenResponse:

    messageId: str
    
    sessionId: str

    contents: list[QianWenContent]

    stopReason: str

    def __init__(self, data: dict):
        # 这里接收 请求器 获得的数据data，转换为自身的各个成员变量
```

仅供理解用，具体实现可以参考这个格式，放到单独的文件里吧，保留一些基本的字段就好了。

这样，用户以后只需要 response.contents 就可以访问响应内容了，上游的数据格式若有改动，我们修改 类的构造函数就可以了。

目前只做 ask 的返回数据类先

2024-03-24 07:09 UTC, old-dream321 commented
实现了你说的所有东西，目前添加了一个新文件用于响应模版，所有响应都已打包为对象，目前对象仍然拥有两种访问方式，“.”与“[]"

2024-03-27 10:44 UTC, leeeduke approved these changes

2024-03-27 10:46 UTC, leeeduke commented
感谢贡献！

2024-03-27 10:46 UTC, merged

2024-03-30 14:56 UTC, leeeduke commented
把你加到了 collaborator，邮件通过一下。以后除了 API（面向用户的）之外的更改（如适配新协议）你直接提交就行了，不需要再提pr（不过不确定的东西可以提pr我看看）。